jenkins:
  systemMessage: "Configuration as Code"
unclassified:
  shell:
    shell: "bash"
  globalLibraries:
    libraries:
      - defaultVersion: "master"
        name: "satqe_pipeline_lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/mkrzyzanowski/blog-001.git"
                traits:
                - "gitBranchDiscovery"    
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
        branchSources {
                git {
                id = 'configuration-as-code'
                remote('https://github.com/mkrzyzanowski/blog-001.git')
                }
      }
}                 
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.3" 





