jenkins:
  systemMessage: "Controlled by Configuration as Code"


jobs:
  - script: >
        multibranchPipelineJob('configuration-as-code') {
        branchSources {
                git {
               
                remote('https://github.com/mkrzyzanowski/blog-001.git')
                }
      }
}
