jenkins:
  systemMessage: "Configuration as Code"
unclassified:
  shell:
    shell: "bash"
  globalLibraries:
    libraries:
      - defaultVersion: "master"
        name: "satqe_pipeline_lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/mkrzyzanowski/blog-001.git"
                traits:
                - "gitBranchDiscovery"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                        branch '*/docker-for-mac'
                        extensions {}
                    }
                  }
              }
          }
      }                
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.3" 





