jenkins:
  systemMessage: "Configuration as Code"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                        branch '*/docker-for-mac'
                        extensions {}
                    }
                  }
              }
          }
      }  
unclassified:
  shell:
    shell: "bash"
  ansibleTowerGlobalConfig:
    towerInstallation:
      - enableDebugging: true
        towerCredentialsId: ansible-tower-jenkins-user  # create these by hand in jenkins
        towerDisplayName: Infra-Ansible-Tower-01
        towerTrustCert: true
        towerURL: https://infra-ansible.example.com
  globalLibraries:
    libraries:
      - defaultVersion: "master"
        name: "satqe_pipeline_lib"
        retriever:
          modernSCM:
            scm:
              git:
                https://github.com/mkrzyzanowski/blog-001.git
                traits:
                - "gitBranchDiscovery"
#                  - branchDiscoveryTrait:
#                      strategyId: 1      






